FilmApp/Controllers/FilmController.cs
using FilmApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace FilmApp.Controllers
{
    public class FilmController : Controller
    {
        private FilmContext _context;
        public FilmController(FilmContext context)
        {
            _context = context;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Save([Bind("Id,Name,CountOfSeries,Img,Treiler,Year,Country,Director,Description")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View();
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Films.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CountOfSeries,Img,Treiler,Year,Country,Director,Description")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index","Home");
            }
            return View(film);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Films.FindAsync(id);
            _context.Films.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }
        private bool FilmExists(int id)
        {
            return _context.Films.Any(e => e.Id == id);
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

FilmApp/Controllers/OverviewController.cs
using FilmApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FilmApp.Controllers
{
    public class OverviewController : Controller
    {
        private FilmContext db;
        public OverviewController(FilmContext context)
        {
            db = context;
        }
        public IActionResult Info(int id)
        {
            Film film = db.Films.Find(id);
            return View(film);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

FilmApp/Controllers/WathchedController.cs
using FilmApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace FilmApp.Controllers
{
    public class WathchedController : Controller
    {
        private readonly FilmContext _context;
        UserManager<IdentityUser> _userManager;
        public WathchedController(FilmContext context,
            UserManager<IdentityUser> manager)
        {
            _userManager = manager;
            _context = context;
        }
        public IActionResult Add(int Id, [Bind("Id,Name,CountOfSeries,Img,Treiler,Year,Country,Director,Description")] Film film)
        {

            var name = HttpContext.User.Identity.Name;
            var users = _context.Users.Where(u => u.Email == name);
            var user = users.FirstOrDefault();
            int id = user.Id;
            var temp = _context.Watcheds.Where(w => w.UserId == id && w.FilmId == Id);
            if (temp.Count() == 0)
            {
                var Watched = new Watched()
                {
                    UserId = id,
                    FilmId = Id
                };
                _context.Watcheds.Add(Watched);
                _context.SaveChanges();
                return View("AddSucsess");
            }
            else
            {
                return View();
            }

            
        }
        public IActionResult Remove(int Id, [Bind("Id,Name,CountOfSeries,Img,Treiler,Year,Country,Director,Description")] Film film)
        {
            var name = HttpContext.User.Identity.Name;
            var users = _context.Users.Where(u => u.Email == name);
            var user = users.FirstOrDefault();
            int id = user.Id;
            var temp = _context.Watcheds.Where(w => w.UserId == id && w.FilmId == Id);
            if (!(temp.Count() == 0))
            {
                var result = temp.FirstOrDefault();
                _context.Watcheds.Remove(result);
                _context.SaveChanges();
                return View("RemoveException");
            }
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

FilmApp/Views/Overview/Info.cshtml
@using FilmApp.Controllers
@model FilmApp.Models.Film;

@{
    ViewData["Title"] = "Info";
}
<div class="flex" style="background-color:#ffffff;height:100%">
    <div class="row flex-nowrap ">
        <div style="width:300px;height:450px;">
            <h4 style="margin-left: 410px;margin-top:10px">@Model.Name</h4>
            <img src="@Model.Img" width="300" height="450" alt="..." style="margin-left: 70px;">
            @if (User.Identity.IsAuthenticated)
            {
                <a style="margin-left: 70px;" asp-action="Add" asp-controller="Wathched" asp-route-id="@Model.Id">Добавить в мои фильмы</a>
                <a style="margin-left: 70px;" asp-action="Remove" asp-controller="Wathched" asp-route-id="@Model.Id">удалить из моих фильмов</a>
            }
        </div>        
        <div style="margin-left: 100px">
            <dl style="margin-top:100px">               
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Year)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Year)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Country)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Country)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Director)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Director)
                </dd>
                @if (Model.CountOfSeries > 1)
                {
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.CountOfSeries)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CountOfSeries)
                    </dd>
                }
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
            <iframe width="500px" height="315" src="@Model.Treiler" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="margin-left:17px"></iframe>
        </div>
    </div>
    @if (User.IsInRole("admin"))
    {
        <a asp-action="Edit" asp-controller="Film" asp-route-id="@Model.Id">Изменить</a>
        <a asp-action="Delete" asp-controller="Film" asp-route-id="@Model.Id">Удалить</a>
       
    }
</div>